-- Convo schema.
--
-- Every row that belongs to a brand carries tenant_id, and every query in the
-- application filters on it. Written for SQLite but deliberately Postgres-shaped:
-- explicit foreign keys, no SQLite-only column affinities, text ids generated by
-- the application, timestamps as ISO-8601 UTC strings.

PRAGMA foreign_keys = ON;

-- ── Tenants ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tenants (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  slug              TEXT NOT NULL UNIQUE,
  description       TEXT,
  -- Agent persona, per brand. Same agent architecture, different voice.
  assistant_name    TEXT NOT NULL DEFAULT 'Assistant',
  brand_voice       TEXT NOT NULL DEFAULT 'warm, precise, and unhurried',
  currency          TEXT NOT NULL DEFAULT 'INR',
  accent_color      TEXT NOT NULL DEFAULT '#1A1C22',
  -- Per-tenant model override; NULL falls back to the platform LLM_PROVIDER.
  llm_provider      TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tenant_users (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email             TEXT NOT NULL UNIQUE,
  password_hash     TEXT NOT NULL,
  password_salt     TEXT NOT NULL,
  display_name      TEXT,
  created_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_users_tenant ON tenant_users(tenant_id);

CREATE TABLE IF NOT EXISTS dashboard_sessions (
  id                TEXT PRIMARY KEY,
  tenant_user_id    TEXT NOT NULL REFERENCES tenant_users(id) ON DELETE CASCADE,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  created_at        TEXT NOT NULL,
  expires_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dashboard_sessions_user ON dashboard_sessions(tenant_user_id);

-- ── Providers ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS provider_connections (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- 'manual' | 'razorpay'  (one row per capability pair; see commerce/registry.ts)
  provider_type     TEXT NOT NULL,
  -- 'catalog' | 'payment' | 'catalog+payment'
  capabilities      TEXT NOT NULL DEFAULT 'catalog+payment',
  -- AES-256-GCM ciphertext of the credential JSON. Never returned to any client.
  credentials_enc   TEXT,
  -- Non-secret display hint, e.g. "rzp_test_••••4f2a". Safe to return.
  credentials_hint  TEXT,
  -- 'never' | 'syncing' | 'ok' | 'error'
  sync_status       TEXT NOT NULL DEFAULT 'never',
  sync_error        TEXT,
  last_synced_at    TEXT,
  is_active         INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  UNIQUE (tenant_id, provider_type)
);
CREATE INDEX IF NOT EXISTS idx_provider_connections_tenant ON provider_connections(tenant_id);

-- ── Catalog ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS products (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- 'manual' | 'razorpay'
  source            TEXT NOT NULL DEFAULT 'manual',
  provider_native_id TEXT,
  name              TEXT NOT NULL,
  description       TEXT,
  -- Minor units (paise for INR). Money is never stored as a float.
  price_minor       INTEGER NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'INR',
  images            TEXT NOT NULL DEFAULT '[]',   -- JSON array of URLs
  stock             INTEGER NOT NULL DEFAULT 0,
  category          TEXT,
  attributes        TEXT NOT NULL DEFAULT '{}',   -- JSON object of display attributes
  is_active         INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  UNIQUE (tenant_id, provider_native_id)
);
CREATE INDEX IF NOT EXISTS idx_products_tenant ON products(tenant_id);
CREATE INDEX IF NOT EXISTS idx_products_tenant_active ON products(tenant_id, is_active);

-- ── Conversations ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS conversations (
  id                  TEXT PRIMARY KEY,
  tenant_id           TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  customer_session_id TEXT NOT NULL,
  started_at          TEXT NOT NULL,
  last_active_at      TEXT NOT NULL,
  UNIQUE (tenant_id, customer_session_id)
);
CREATE INDEX IF NOT EXISTS idx_conversations_tenant ON conversations(tenant_id);

CREATE TABLE IF NOT EXISTS messages (
  id                TEXT PRIMARY KEY,
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- 'user' | 'assistant'
  role              TEXT NOT NULL,
  content           TEXT NOT NULL DEFAULT '',
  -- JSON array of {id,name,input} the model requested this turn
  tool_calls        TEXT,
  -- JSON array of {tool_use_id,content,is_error} handed back to the model
  tool_results      TEXT,
  -- JSON array of rendered UI components for replay on reload
  ui                TEXT,
  created_at        TEXT NOT NULL,
  seq               INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, seq);

-- Provenance: the product ids the agent has actually seen this session. Cart
-- writes and presentation payloads accept nothing else. (commerce-agents gates.)
CREATE TABLE IF NOT EXISTS seen_products (
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  product_id        TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  seen_at           TEXT NOT NULL,
  PRIMARY KEY (conversation_id, product_id)
);

-- ── Cart and orders ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS carts (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  -- 'open' | 'locked' | 'converted' | 'abandoned'
  status            TEXT NOT NULL DEFAULT 'open',
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_carts_conversation ON carts(conversation_id);

CREATE TABLE IF NOT EXISTS cart_items (
  id                TEXT PRIMARY KEY,
  cart_id           TEXT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  product_id        TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity          INTEGER NOT NULL,
  -- Price snapshot at add time, in minor units. Never used to charge: checkout
  -- re-reads the catalog. Kept so the agent can notice a price move.
  unit_price_minor  INTEGER NOT NULL,
  added_at          TEXT NOT NULL,
  UNIQUE (cart_id, product_id)
);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart ON cart_items(cart_id);

CREATE TABLE IF NOT EXISTS orders (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  cart_id           TEXT NOT NULL REFERENCES carts(id) ON DELETE RESTRICT,
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  -- Authoritative amount, recomputed server-side from catalog prices.
  total_amount_minor INTEGER NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'INR',
  -- 'created' | 'awaiting_payment' | 'paid' | 'failed' | 'cancelled' | 'refunded'
  status            TEXT NOT NULL DEFAULT 'created',
  provider_type     TEXT NOT NULL,
  provider_order_id TEXT,
  provider_payment_id TEXT,
  -- Frozen line items as JSON, so an order stays readable if the catalog changes.
  line_items        TEXT NOT NULL DEFAULT '[]',
  failure_reason    TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_orders_tenant ON orders(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_provider_order ON orders(provider_order_id);

-- ── Audit ───────────────────────────────────────────────────────────────────

-- Append-only. Nothing in the application updates or deletes a row here.
CREATE TABLE IF NOT EXISTS audit_log (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  conversation_id   TEXT,
  cart_id           TEXT,
  order_id          TEXT,
  -- cart.locked | order.created | payment.attempted | payment.confirmed |
  -- payment.failed | payment.signature_rejected | order.refunded |
  -- checkout.blocked | catalog.synced | agent.tool_held
  action_type       TEXT NOT NULL,
  amount_minor      INTEGER,
  currency          TEXT,
  -- 'ok' | 'blocked' | 'failed'
  outcome           TEXT NOT NULL,
  -- What the agent said it was doing, when the entry came from a tool call.
  reasoning         TEXT,
  -- JSON blob of non-secret detail.
  detail            TEXT,
  created_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_tenant ON audit_log(tenant_id, created_at);
