-- Convo schema.
--
-- Every row that belongs to a brand carries tenant_id, and every query in the
-- application filters on it. Written for SQLite but deliberately Postgres-shaped:
-- explicit foreign keys, no SQLite-only column affinities, text ids generated by
-- the application, timestamps as ISO-8601 UTC strings.

PRAGMA foreign_keys = ON;

-- ── Tenants ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tenants (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  slug              TEXT NOT NULL UNIQUE,
  description       TEXT,
  currency          TEXT NOT NULL DEFAULT 'INR',
  /*
   * Four columns kept for existing databases and read by nothing.
   *
   * They configured a per-brand assistant — its name, its register, its
   * colour, its model — back when every brand had a chat page of its own.
   * One agent serves the whole marketplace now, so a per-brand persona would
   * mean the shop changing voice as the customer moved between shelves.
   * SQLite cannot drop a column without rebuilding the table, and rebuilding
   * it to delete four defaults nothing reads is not worth the risk to live
   * catalogues; a Postgres migration drops them.
   */
  assistant_name    TEXT NOT NULL DEFAULT 'Assistant',
  brand_voice       TEXT NOT NULL DEFAULT 'warm, precise, and unhurried',
  accent_color      TEXT NOT NULL DEFAULT '#1A1C22',
  llm_provider      TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tenant_users (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email             TEXT NOT NULL UNIQUE,
  password_hash     TEXT NOT NULL,
  password_salt     TEXT NOT NULL,
  display_name      TEXT,
  created_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_users_tenant ON tenant_users(tenant_id);

CREATE TABLE IF NOT EXISTS dashboard_sessions (
  id                TEXT PRIMARY KEY,
  tenant_user_id    TEXT NOT NULL REFERENCES tenant_users(id) ON DELETE CASCADE,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  created_at        TEXT NOT NULL,
  expires_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dashboard_sessions_user ON dashboard_sessions(tenant_user_id);

-- ── Providers ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS provider_connections (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- 'manual' | 'razorpay'  (one row per capability pair; see commerce/registry.ts)
  provider_type     TEXT NOT NULL,
  -- 'catalog' | 'payment' | 'catalog+payment'
  capabilities      TEXT NOT NULL DEFAULT 'catalog+payment',
  -- AES-256-GCM ciphertext of the credential JSON. Never returned to any client.
  credentials_enc   TEXT,
  -- Non-secret display hint, e.g. "rzp_test_••••4f2a". Safe to return.
  credentials_hint  TEXT,
  -- 'never' | 'syncing' | 'ok' | 'error'
  sync_status       TEXT NOT NULL DEFAULT 'never',
  sync_error        TEXT,
  last_synced_at    TEXT,
  is_active         INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  UNIQUE (tenant_id, provider_type)
);
CREATE INDEX IF NOT EXISTS idx_provider_connections_tenant ON provider_connections(tenant_id);

-- ── Catalog ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS products (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- 'manual' | 'razorpay'
  source            TEXT NOT NULL DEFAULT 'manual',
  provider_native_id TEXT,
  name              TEXT NOT NULL,
  description       TEXT,
  -- Minor units (paise for INR). Money is never stored as a float.
  price_minor       INTEGER NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'INR',
  images            TEXT NOT NULL DEFAULT '[]',   -- JSON array of URLs
  stock             INTEGER NOT NULL DEFAULT 0,
  category          TEXT,
  attributes        TEXT NOT NULL DEFAULT '{}',   -- JSON object of display attributes
  is_active         INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  UNIQUE (tenant_id, provider_native_id)
);
CREATE INDEX IF NOT EXISTS idx_products_tenant ON products(tenant_id);
CREATE INDEX IF NOT EXISTS idx_products_tenant_active ON products(tenant_id, is_active);

-- ── Conversations ──────────────────────────────────────────────────────────
--
-- A shopper talks to Convo, not to a brand, so nothing below carries a
-- tenant_id except where it names which brand a product or an order belongs
-- to. Tenant isolation has not weakened — it has moved: a brand still cannot
-- read another brand's catalogue, orders or ledger. What is shared is the
-- shopper's conversation, which belongs to the platform.

-- A shopper has many of these. customer_session_id was UNIQUE when a shopper
-- got exactly one conversation that ran forever; it is only an index now.
CREATE TABLE IF NOT EXISTS conversations (
  id                  TEXT PRIMARY KEY,
  customer_session_id TEXT NOT NULL,
  -- What the shopper sees in the chat list. Taken from their first message.
  title               TEXT,
  started_at          TEXT NOT NULL,
  last_active_at      TEXT NOT NULL,
  -- Hidden from the list, never removed. Orders point at the conversation they
  -- were placed in, and a paid order must not disappear because somebody
  -- tidied their sidebar.
  archived_at         TEXT
);
CREATE INDEX IF NOT EXISTS idx_conversations_customer
  ON conversations(customer_session_id, last_active_at DESC);

CREATE TABLE IF NOT EXISTS messages (
  id                TEXT PRIMARY KEY,
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  -- 'user' | 'assistant'
  role              TEXT NOT NULL,
  content           TEXT NOT NULL DEFAULT '',
  tool_calls        TEXT,
  tool_results      TEXT,
  ui                TEXT,
  created_at        TEXT NOT NULL,
  seq               INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, seq);

-- Provenance: the product ids the agent has actually seen this conversation.
-- tenant_id records which brand the product belongs to, not who owns the row.
CREATE TABLE IF NOT EXISTS seen_products (
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  product_id        TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  seen_at           TEXT NOT NULL,
  PRIMARY KEY (conversation_id, product_id)
);

-- ── Cart and orders ─────────────────────────────────────────────────────────

-- One cart per shopper, holding goods from any number of brands.
--
-- Per shopper, not per conversation. The chat is where the shopping gets talked
-- about; the basket belongs to the person, and follows them into whatever chat
-- they open next. Keyed the other way, opening a new chat would quietly abandon
-- whatever was in the old one, which is not a thing shops do.
CREATE TABLE IF NOT EXISTS carts (
  id                  TEXT PRIMARY KEY,
  customer_session_id TEXT NOT NULL,
  -- 'open' | 'locked' | 'converted' | 'abandoned'
  status              TEXT NOT NULL DEFAULT 'open',
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_carts_customer ON carts(customer_session_id, status);

CREATE TABLE IF NOT EXISTS cart_items (
  id                TEXT PRIMARY KEY,
  cart_id           TEXT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  -- Which brand sells this line. Used to split the cart at checkout.
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  product_id        TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity          INTEGER NOT NULL,
  -- Price snapshot at add time. Never used to charge: checkout re-reads the
  -- catalogue. Kept so the agent can notice a price move.
  unit_price_minor  INTEGER NOT NULL,
  added_at          TEXT NOT NULL,
  UNIQUE (cart_id, product_id)
);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart ON cart_items(cart_id);

-- One order per brand per checkout. A cart spanning three brands is three
-- orders sharing a checkout_id, because each brand has its own payment
-- account and Convo is not the merchant of record.
CREATE TABLE IF NOT EXISTS orders (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  cart_id           TEXT NOT NULL REFERENCES carts(id) ON DELETE RESTRICT,
  conversation_id   TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  -- Groups the orders staged together by one checkout.
  checkout_id       TEXT NOT NULL,
  -- Which signed mandate authorised this, when an agent bought rather than a
  -- person. Null for an ordinary checkout. Spend is tallied against it, so a
  -- budget depletes across checkouts instead of resetting every time.
  mandate_id        TEXT,
  -- Authoritative amount for this brand's share, recomputed server-side.
  total_amount_minor INTEGER NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'INR',
  -- 'created' | 'awaiting_payment' | 'paid' | 'failed' | 'cancelled' | 'refunded'
  status            TEXT NOT NULL DEFAULT 'created',
  provider_type     TEXT NOT NULL,
  provider_order_id TEXT,
  provider_payment_id TEXT,
  line_items        TEXT NOT NULL DEFAULT '[]',
  shipping_address  TEXT,
  failure_reason    TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_orders_tenant ON orders(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_checkout ON orders(checkout_id);
CREATE INDEX IF NOT EXISTS idx_orders_provider_order ON orders(provider_order_id);

-- ── Audit ───────────────────────────────────────────────────────────────────

-- Append-only. Nothing in the application updates or deletes a row here.
CREATE TABLE IF NOT EXISTS audit_log (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  conversation_id   TEXT,
  cart_id           TEXT,
  order_id          TEXT,
  -- cart.locked | order.created | payment.attempted | payment.confirmed |
  -- payment.failed | payment.signature_rejected | order.refunded |
  -- checkout.blocked | catalog.synced | agent.tool_held
  action_type       TEXT NOT NULL,
  amount_minor      INTEGER,
  currency          TEXT,
  -- 'ok' | 'blocked' | 'failed'
  outcome           TEXT NOT NULL,
  -- What the agent said it was doing, when the entry came from a tool call.
  reasoning         TEXT,
  -- JSON blob of non-secret detail.
  detail            TEXT,
  created_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_tenant ON audit_log(tenant_id, created_at);

-- ── Public API keys ─────────────────────────────────────────────────────────

-- A key is stored only as a SHA-256 digest: Convo cannot recover one, and a
-- copy of this table is not a set of credentials. `prefix` is the first
-- characters of the key, kept in clear so a merchant can tell two keys apart
-- and so a leaked key can be matched to its row without holding the secret.
CREATE TABLE IF NOT EXISTS api_keys (
  id                TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name              TEXT NOT NULL,
  key_hash          TEXT NOT NULL UNIQUE,
  prefix            TEXT NOT NULL,
  -- 'read' | 'write'. A write key can also read.
  scope             TEXT NOT NULL DEFAULT 'write',
  created_at        TEXT NOT NULL,
  last_used_at      TEXT,
  revoked_at        TEXT
);
CREATE INDEX IF NOT EXISTS idx_api_keys_tenant ON api_keys(tenant_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys(key_hash);

-- The merchant's own id for a product, so a re-sync updates instead of
-- duplicating. Distinct from provider_native_id, which belongs to a connected
-- provider rather than to the merchant's own system.
ALTER TABLE products ADD COLUMN external_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_products_external
  ON products(tenant_id, external_id) WHERE external_id IS NOT NULL;

-- A brand can take its catalogue from one provider and its payments from
-- another — Shopify for products, Razorpay for money — so the two roles are
-- separate flags rather than one `is_active`.
ALTER TABLE provider_connections ADD COLUMN is_catalog_source INTEGER NOT NULL DEFAULT 0;
ALTER TABLE provider_connections ADD COLUMN is_payment_processor INTEGER NOT NULL DEFAULT 0;

-- A brand selling digital goods turns this off; everyone else ships.
ALTER TABLE tenants ADD COLUMN requires_shipping INTEGER NOT NULL DEFAULT 1;

-- A brand signed up for a dashboard, not for a shelf beside a competitor.
-- Nothing appears in the marketplace until the brand turns this on.
ALTER TABLE tenants ADD COLUMN is_listed INTEGER NOT NULL DEFAULT 0;
